# Generated by Django 3.1.4 on 2020-12-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=50, verbose_name='Текст')),
                ('is_published', models.BooleanField(default=True, help_text='Заметка, если ты дошла до этого пункта, то ты очень упорная, я ценью это.Подсказка: один из этих полей явно отрицательны, нужно их поменять на True значение, и ты дошла до явной победы. Теперь всего лишь нужно прочесть, по прежней ссылке.', verbose_name='Published')),
            ],
            options={
                'verbose_name': 'notes',
                'verbose_name_plural': 'Заметки',
                'db_table': 'note',
            },
        ),
    ]
