# Generated by Django 3.1.4 on 2020-12-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notedb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
